// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teste.CrmEducacional.Domain.Configurations;

#nullable disable

namespace Teste.CrmEducacional.Api.Migrations
{
    [DbContext(typeof(TesteCrmEducacionalDbContext))]
    [Migration("20250130231652_RelacionamentosEntity")]
    partial class RelacionamentosEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teste.CrmEducacional.Domain.Entities.Candidato", b =>
                {
                    b.Property<long>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCandidato"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCandidato");

                    b.ToTable("Candidatos", "public");
                });

            modelBuilder.Entity("Teste.CrmEducacional.Domain.Entities.Curso", b =>
                {
                    b.Property<long>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCurso"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("VagasDisponivel")
                        .HasColumnType("bigint");

                    b.HasKey("IdCurso");

                    b.ToTable("Cursos", "public");
                });

            modelBuilder.Entity("Teste.CrmEducacional.Domain.Entities.Inscricao", b =>
                {
                    b.Property<long>("IdInscricao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdInscricao"));

                    b.Property<long>("CandidatoId")
                        .HasColumnType("bigint");

                    b.Property<long>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroInscricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProcessoSeletivoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdInscricao");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("ProcessoSeletivoId");

                    b.ToTable("Inscricoes", "public");
                });

            modelBuilder.Entity("Teste.CrmEducacional.Domain.Entities.ProcessoSeletivo", b =>
                {
                    b.Property<long>("IdProcessoSeletivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProcessoSeletivo"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdProcessoSeletivo");

                    b.ToTable("ProcessoSeletivo", "public");
                });

            modelBuilder.Entity("Teste.CrmEducacional.Domain.Entities.Inscricao", b =>
                {
                    b.HasOne("Teste.CrmEducacional.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teste.CrmEducacional.Domain.Entities.Curso", "Curso")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teste.CrmEducacional.Domain.Entities.ProcessoSeletivo", "ProcessoSeletivo")
                        .WithMany("Inscricoes")
                        .HasForeignKey("ProcessoSeletivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Curso");

                    b.Navigation("ProcessoSeletivo");
                });

            modelBuilder.Entity("Teste.CrmEducacional.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("Teste.CrmEducacional.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("Teste.CrmEducacional.Domain.Entities.ProcessoSeletivo", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
